events {}

http {
  map $arg_x_server $query_backend {
    "A" ws_server_a;
    "B" ws_server_b;
    default ws_server_a;
  }

  map $http_x_server $header_backend {
    "A" ws_server_a;
    "B" ws_server_b;
    default "";
  }

  map $header_backend $backend {
    "" $query_backend;
    default $header_backend;
  }

  upstream ws_server_a {
    server 172.17.0.1:3000;
  }

  upstream ws_server_b {
    server 172.17.0.1:3001;
  }

  server {
    listen 80;

    add_header X-Server 'A';

    location /socket.io/ {
      proxy_pass http://$backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-Server $http_x_server;
    }
  }
}
