events {}

http {
  map $arg_x_server $query_backend {
    "A" server_a;
    "B" server_b;
    default api_servers;
  }

  map $http_x_server $header_backend {
    "A" server_a;
    "B" server_b;
    default "";
  }

  map $header_backend $backend {
    "" $query_backend;
    default $header_backend;
  }

  upstream server_a {
    server 172.17.0.1:3000;
  }

  upstream server_b {
    server 172.17.0.1:3001;
  }

  upstream api_servers {
    server 172.17.0.1:3000;
    server 172.17.0.1:3001;
  }

  server {
    listen 80;

    add_header X-Server 'A';

    location / {
      proxy_pass http://$backend;
      proxy_http_version 1.1;

      # REQUIRED for SSE
      proxy_buffering off;
      proxy_cache off;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
  }
}
